export const LOGIN = 'LOGIN'
export const SIGNUP = 'SIGNUP'
export const LOGOUT = 'LOGOUT'
export const GET_USER = 'GET_USER'
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const SAVE_PRODUCT = 'SAVE_PRODUCT'